-- Operational store for the customer-service agent.
--   core: read-mostly mirror of the bank, reloaded from silver by `python -m data_pipeline.load`
--         (which builds it as core_staging and swaps it in, so a failed load changes nothing).
--         Its only writer is khipear (postgres/transfers.py): a confirmed transfer changes two
--         balances and adds two movements, a confirmed service payment marks its bill paid, and
--         a reload puts the dataset's state back.
--   ops:  written only by the agent's tools; append-only or audited. Never reloaded.
-- Where every table comes from is in its COMMENT ('provenance: ...'). The organizer's dataset is
-- itself synthetic. Rows seeded by the team (demo scenarios) carry is_synthetic_fixture = true.

DROP SCHEMA IF EXISTS core CASCADE;
CREATE SCHEMA core;
CREATE SCHEMA IF NOT EXISTS ops;

CREATE TABLE core.customers (
    customer_id            text PRIMARY KEY,
    document_type          text,
    document_number        text,
    first_name             text,
    last_name              text,
    date_of_birth          date,
    email                  text,
    mobile_phone           text,
    city                   text,
    country                text NOT NULL,
    detected_accent        text,
    preferred_language     text NOT NULL DEFAULT 'es',
    segment                text,
    customer_status        text,
    registration_date      date,
    is_synthetic_fixture   boolean NOT NULL DEFAULT false
);
COMMENT ON TABLE core.customers IS
    'provenance: organizer dataset; preferred_language is a team assumption (es); demo rows are team fixtures';

CREATE TABLE core.products (
    product_id             text PRIMARY KEY,
    customer_id            text NOT NULL REFERENCES core.customers,
    product_type           text NOT NULL,
    product_number_last4   text,
    account_number         text,            -- savings and checking only: how a transfer names it
    currency               text,
    current_balance        numeric(15, 2),
    credit_limit           numeric(15, 2),
    product_status         text,
    interest_rate          numeric(6, 2),   -- annual %, NULL where the product has none
    opening_date           date,
    expiration_date        date,            -- cards and loans only
    days_past_due          integer,         -- credit cards and loans only
    is_synthetic_fixture   boolean NOT NULL DEFAULT false
);
CREATE INDEX ON core.products (customer_id);
CREATE INDEX ON core.products (account_number);
COMMENT ON TABLE core.products IS
    'provenance: organizer dataset; demo rows are team fixtures';

CREATE TABLE core.transactions (
    transaction_id         text PRIMARY KEY,
    customer_id            text NOT NULL REFERENCES core.customers,
    product_id             text,
    transaction_date       timestamp NOT NULL,
    transaction_type       text,
    transaction_category   text,
    amount                 numeric(15, 2) NOT NULL,
    currency               text NOT NULL,
    amount_usd             numeric(15, 2),
    channel                text,
    merchant_name          text,
    transaction_country    text,
    transaction_city       text,
    transaction_status     text NOT NULL,
    response_code          text,
    is_fraud               boolean,
    fraud_score            numeric(5, 2),
    is_synthetic_fixture   boolean NOT NULL DEFAULT false
);
CREATE INDEX ON core.transactions (customer_id, transaction_date DESC);
CREATE INDEX ON core.transactions (transaction_date);  -- the dataset's last day, for every window
COMMENT ON TABLE core.transactions IS
    'provenance: organizer dataset, transaction_category completed from the merchant in silver; demo rows are team fixtures';

-- Statement and payment schedule of every credit card and loan. The organizer's data has no due
-- dates, statements or installments: these are generated by a fixed rule in data_pipeline/load.py
-- from the product's balance, rate and days_past_due, as of the dataset's last day.
CREATE TABLE core.billing (
    product_id             text PRIMARY KEY REFERENCES core.products,
    customer_id            text NOT NULL REFERENCES core.customers,
    as_of                  date NOT NULL,
    statement_date         date NOT NULL,
    due_date               date NOT NULL,
    statement_balance      numeric(15, 2),          -- cards only
    minimum_payment        numeric(15, 2) NOT NULL, -- cards: minimum due; loans: installment
    past_due_amount        numeric(15, 2) NOT NULL,
    remaining_installments integer,                 -- loans only
    provenance             text NOT NULL DEFAULT 'team_generated'
);
CREATE INDEX ON core.billing (customer_id);
COMMENT ON TABLE core.billing IS
    'provenance: team-generated by a deterministic rule over organizer products (illustrative, not bank records)';

-- Services a customer can pay from an account (khipear, kind pay_service) and the bills waiting
-- for each customer. The organizer's data has neither: the catalog is fixed here and the bills
-- are generated by a fixed rule in data_pipeline/load.py for every customer with an account.
CREATE TABLE core.service_billers (
    biller_id              text PRIMARY KEY,
    name                   text NOT NULL,
    category               text NOT NULL UNIQUE     -- how the customer names it: luz, agua...
);
INSERT INTO core.service_billers VALUES
    ('SVC-LUZ', 'Servicios Públicos Luz', 'luz'),
    ('SVC-AGUA', 'Servicios Públicos Agua', 'agua'),
    ('SVC-TEL', 'Empresa Telefónica', 'teléfono'),
    ('SVC-NET', 'Internet Plus', 'internet'),
    ('SVC-TV', 'Cable TV', 'cable');
COMMENT ON TABLE core.service_billers IS
    'provenance: team-defined catalog (the organizer data only names these as merchants)';

CREATE TABLE core.service_bills (
    bill_id                text PRIMARY KEY,
    customer_id            text NOT NULL REFERENCES core.customers,
    biller_id              text NOT NULL REFERENCES core.service_billers,
    reference              text NOT NULL,           -- the customer's contract with the biller
    amount                 numeric(15, 2) NOT NULL CHECK (amount > 0),
    currency               text NOT NULL,
    due_date               date NOT NULL,
    status                 text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    paid_at                timestamptz
);
CREATE INDEX ON core.service_bills (customer_id, status);
COMMENT ON TABLE core.service_bills IS
    'provenance: team-generated by a deterministic rule over organizer products (illustrative, not bank records)';

CREATE TABLE core.fx_rates (
    date                   date NOT NULL,
    source_currency        text NOT NULL,
    target_currency        text NOT NULL,
    exchange_rate          numeric(14, 6) NOT NULL,
    buy_rate               numeric(14, 6),
    sell_rate              numeric(14, 6),
    PRIMARY KEY (date, source_currency, target_currency)
);
COMMENT ON TABLE core.fx_rates IS 'provenance: organizer dataset';

-- Derived from digital_events: one row per app/web session (evidence for "was it you?").
CREATE TABLE core.app_sessions (
    session_id             text PRIMARY KEY,
    customer_id            text NOT NULL REFERENCES core.customers,
    started_at             timestamp NOT NULL,
    ended_at               timestamp NOT NULL,
    channel                text,
    platform               text,
    ip_country             text,
    ip_city                text,
    had_login              boolean NOT NULL,
    events                 integer NOT NULL,
    is_synthetic_fixture   boolean NOT NULL DEFAULT false
);
CREATE INDEX ON core.app_sessions (customer_id, started_at DESC);
COMMENT ON TABLE core.app_sessions IS
    'provenance: derived in the pipeline from organizer digital_events; demo rows are team fixtures';

-- Derived from interactions, complaints and surveys (which are not loaded themselves): context
-- for escalation rules and the case file.
CREATE TABLE core.customer_service_summary (
    customer_id               text PRIMARY KEY REFERENCES core.customers,
    contacts_in_window        integer NOT NULL,
    escalated_contacts        integer NOT NULL,
    last_contact_at           timestamp,
    last_contact_reason       text,
    open_complaints           integer NOT NULL,
    unrecognized_charge_complaints integer NOT NULL,
    is_repeat_complainer      boolean NOT NULL,
    last_csat                 integer
);
COMMENT ON TABLE core.customer_service_summary IS
    'provenance: derived in the pipeline from organizer interactions, complaints and surveys';

-- Customer-service history (organizer data). Only the columns the agent may talk about.
CREATE TABLE core.complaints (
    complaint_id           text PRIMARY KEY,
    customer_id            text NOT NULL REFERENCES core.customers,
    creation_date          timestamp NOT NULL,
    case_type              text,
    category               text,
    subcategory            text,
    reception_channel      text,
    affected_product_id    text,
    description            text,
    claimed_amount         numeric(15, 2),
    currency               text,
    priority               text,
    status                 text NOT NULL,
    first_response_date    timestamp,
    resolution_date        timestamp,
    closing_date           timestamp,
    sla_breached           boolean,
    resolution_days        integer,
    resolution             text,
    compensation_granted   numeric(15, 2),
    resolution_satisfaction integer,
    is_repeat_complainer   boolean
);
CREATE INDEX ON core.complaints (customer_id, creation_date DESC);
COMMENT ON TABLE core.complaints IS 'provenance: organizer dataset';


-- ---------- ops: written by the agent's tools ----------

CREATE TABLE IF NOT EXISTS ops.sessions (
    session_id             uuid PRIMARY KEY,
    customer_id            text NOT NULL,
    issued_at              timestamptz NOT NULL DEFAULT now(),
    expires_at             timestamptz NOT NULL,
    step_up_at             timestamptz
);

-- Two-phase confirmation: a tool proposes, the customer confirms in the UI (never the LLM).
CREATE TABLE IF NOT EXISTS ops.pending_confirmations (
    confirmation_id        uuid PRIMARY KEY,
    session_id             uuid NOT NULL REFERENCES ops.sessions,
    action                 text NOT NULL,
    payload                jsonb NOT NULL,
    created_at             timestamptz NOT NULL DEFAULT now(),
    expires_at             timestamptz NOT NULL,
    confirmed_at           timestamptz
);

-- Khipear: one row per money movement the agent proposed, through its whole life. The customer
-- confirms with a button (never the LLM); `summary` is what that button showed them.
-- For kind pay_service the destination is a bill: destination_product_id holds its bill_id and
-- destination_customer_id the biller_id.
CREATE TABLE IF NOT EXISTS ops.transfers (
    transfer_id            uuid PRIMARY KEY,
    customer_id            text NOT NULL,
    kind                   text NOT NULL CHECK (kind IN ('own_accounts', 'pay_debt', 'third_party')),
    origin_product_id      text NOT NULL,
    destination_product_id text NOT NULL,
    destination_customer_id text NOT NULL,
    amount                 numeric(15, 2) NOT NULL CHECK (amount > 0),
    currency               text NOT NULL,
    amount_usd             numeric(15, 2),
    summary                jsonb NOT NULL,
    status                 text NOT NULL DEFAULT 'proposed'
                           CHECK (status IN ('proposed', 'executed', 'cancelled', 'expired', 'blocked')),
    status_reason          text,
    created_at             timestamptz NOT NULL DEFAULT now(),
    expires_at             timestamptz NOT NULL,
    executed_at            timestamptz,
    origin_balance_after   numeric(15, 2)
);
CREATE INDEX IF NOT EXISTS transfers_customer_day ON ops.transfers (customer_id, executed_at);

CREATE TABLE IF NOT EXISTS ops.card_actions (
    action_id              uuid PRIMARY KEY,
    product_id             text NOT NULL,
    customer_id            text NOT NULL,
    action                 text NOT NULL CHECK (action IN ('freeze', 'unfreeze', 'cancel')),
    requested_at           timestamptz NOT NULL DEFAULT now(),
    verified_at            timestamptz
);

CREATE TABLE IF NOT EXISTS ops.provisional_credits (
    credit_id              uuid PRIMARY KEY,
    idempotency_key        text NOT NULL UNIQUE,
    customer_id            text NOT NULL,
    transaction_id         text NOT NULL,
    amount                 numeric(15, 2) NOT NULL,
    currency               text NOT NULL,
    reason                 text NOT NULL,
    status                 text NOT NULL,
    created_at             timestamptz NOT NULL DEFAULT now(),
    verified_at            timestamptz
);

CREATE TABLE IF NOT EXISTS ops.disputes (
    dispute_id             uuid PRIMARY KEY,
    customer_id            text NOT NULL,
    transaction_id         text NOT NULL,
    investigation_result   jsonb NOT NULL,
    status                 text NOT NULL,
    sla_due_at             timestamptz,
    tracking_token         text UNIQUE,
    created_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ops.handoff_cases (
    case_id                uuid PRIMARY KEY,
    customer_id            text NOT NULL,
    dispute_id             uuid REFERENCES ops.disputes,
    priority               text NOT NULL,
    reason_codes           text[] NOT NULL,
    case_file              jsonb NOT NULL,
    status                 text NOT NULL DEFAULT 'open',
    created_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ops.conversations (
    conversation_id        uuid PRIMARY KEY,
    session_id             uuid REFERENCES ops.sessions,
    channel                text NOT NULL,
    language               text,
    started_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ops.messages (
    message_id             bigserial PRIMARY KEY,
    conversation_id        uuid NOT NULL REFERENCES ops.conversations,
    role                   text NOT NULL,
    content                text NOT NULL,
    created_at             timestamptz NOT NULL DEFAULT now()
);

-- Audit trail: every proposal, policy decision and verified outcome.
CREATE TABLE IF NOT EXISTS ops.decision_log (
    log_id                 bigserial PRIMARY KEY,
    conversation_id        uuid,
    tool                   text NOT NULL,
    proposed               jsonb NOT NULL,
    policy_decision        text NOT NULL CHECK (policy_decision IN ('allowed', 'blocked', 'needs_confirmation', 'escalated')),
    policy_reason          text,
    executed               boolean NOT NULL DEFAULT false,
    verified               boolean NOT NULL DEFAULT false,
    created_at             timestamptz NOT NULL DEFAULT now()
);

-- ---------- ops: actions the agent proposes and the customer confirms ----------
-- Every statement here is safe to run again, so it is also the migration for a database that
-- already has the rest of ops (see migrations/001_actions.sql, which must stay identical).
-- BEGIN actions migration

ALTER TABLE ops.card_actions DROP CONSTRAINT IF EXISTS card_actions_action_check;
ALTER TABLE ops.card_actions
    ADD CONSTRAINT card_actions_action_check CHECK (action IN ('freeze', 'unfreeze', 'cancel'));
CREATE INDEX IF NOT EXISTS card_actions_product_idx ON ops.card_actions (product_id, requested_at DESC);

-- One row per proposed action, grouped in a batch the customer confirms once.
CREATE TABLE IF NOT EXISTS ops.actions (
    action_id              uuid PRIMARY KEY,
    batch_id               uuid NOT NULL,
    position               integer NOT NULL,
    customer_id            text NOT NULL,
    conversation_id        text,
    action                 text NOT NULL,
    params                 jsonb NOT NULL,
    view                   jsonb NOT NULL DEFAULT '{}',
    decision               text NOT NULL CHECK (decision IN ('allowed', 'needs_confirmation', 'blocked', 'escalated')),
    reason                 text,
    status                 text NOT NULL CHECK (status IN (
        'awaiting_confirmation', 'confirmed', 'executing', 'verified', 'failed',
        'cancelled', 'expired', 'refused', 'escalated', 'skipped')),
    language               text NOT NULL DEFAULT 'es',
    idempotency_key        text NOT NULL UNIQUE,
    attempts               integer NOT NULL DEFAULT 0,
    result                 jsonb,
    created_at             timestamptz NOT NULL DEFAULT now(),
    expires_at             timestamptz NOT NULL,
    confirmed_at           timestamptz,
    finished_at            timestamptz
);
CREATE INDEX IF NOT EXISTS actions_batch_idx ON ops.actions (batch_id, position);
CREATE INDEX IF NOT EXISTS actions_customer_idx ON ops.actions (customer_id, created_at DESC);

-- What the customer chose for alerts and reminders.
CREATE TABLE IF NOT EXISTS ops.preferences (
    customer_id            text NOT NULL,
    key                    text NOT NULL,
    value                  jsonb NOT NULL,
    updated_at             timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (customer_id, key)
);

-- Messages the system sent (or tried to). `accepted` means the mail server took the message,
-- not that it reached anyone; `destination` is the registered contact, masked, and
-- `delivered_to` the demo inbox it really went to.
CREATE TABLE IF NOT EXISTS ops.outbox (
    message_id             bigserial PRIMARY KEY,
    customer_id            text NOT NULL,
    action_id              uuid,
    channel                text NOT NULL CHECK (channel IN ('email', 'sms')),
    destination            text NOT NULL,
    delivered_to           text,
    template               text NOT NULL,
    language               text NOT NULL,
    subject                text NOT NULL,
    body                   text NOT NULL,
    mode                   text NOT NULL CHECK (mode IN ('simulated', 'smtp')),
    status                 text NOT NULL CHECK (status IN ('queued', 'accepted', 'failed')),
    provider_reply         text,
    attempts               integer NOT NULL DEFAULT 0,
    created_at             timestamptz NOT NULL DEFAULT now(),
    sent_at                timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS outbox_action_idx ON ops.outbox (action_id) WHERE action_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS outbox_customer_idx ON ops.outbox (customer_id, created_at DESC);

-- END actions migration

-- ---------- ops: khipear pays service bills ----------
-- Safe to run again; also the migration for a database that already has ops.transfers (see
-- migrations/002_services.sql, which must stay identical).
-- BEGIN services migration

ALTER TABLE ops.transfers DROP CONSTRAINT IF EXISTS transfers_kind_check;
ALTER TABLE ops.transfers ADD CONSTRAINT transfers_kind_check
    CHECK (kind IN ('own_accounts', 'pay_debt', 'third_party', 'pay_service'));

-- END services migration

-- ---------- read-only role for SQL written by the LLM (see app/domain/sql_scope.py) ----------
-- SELECT on core only: no ops, no writes. Whose rows a query sees is decided in code, not here.
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'dwh_reader') THEN
        CREATE ROLE dwh_reader NOLOGIN;
    END IF;
END
$$;
GRANT dwh_reader TO CURRENT_USER;  -- lets a non-superuser (Cloud SQL) run SET ROLE dwh_reader
GRANT USAGE ON SCHEMA core TO dwh_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA core TO dwh_reader;

-- BEGIN chat memory migration
ALTER TABLE ops.conversations ADD COLUMN IF NOT EXISTS customer_id text;
ALTER TABLE ops.conversations ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE ops.conversations ADD COLUMN IF NOT EXISTS skill text;
ALTER TABLE ops.conversations ADD COLUMN IF NOT EXISTS outcome text;
ALTER TABLE ops.conversations ADD COLUMN IF NOT EXISTS last_message_at timestamptz;
ALTER TABLE ops.messages ADD COLUMN IF NOT EXISTS skill text;
CREATE INDEX IF NOT EXISTS conversations_by_customer ON ops.conversations (customer_id, last_message_at DESC);
CREATE INDEX IF NOT EXISTS messages_by_conversation ON ops.messages (conversation_id, message_id);
-- END chat memory migration

-- BEGIN chat memory hidden migration
ALTER TABLE ops.conversations ADD COLUMN IF NOT EXISTS hidden_at timestamptz;
CREATE INDEX IF NOT EXISTS conversations_visible ON ops.conversations (customer_id, last_message_at DESC) WHERE hidden_at IS NULL;
-- END chat memory hidden migration
