"""MCP server for the `balance_inquiry` skill: balances, debts and the customer's own profile.

python -m app.adapters.inbound.mcp.accounts   # stdio, e.g. for MCP Inspector
"""

from typing import Literal

from fastmcp import Context, FastMCP

from app.adapters.inbound.mcp import session_customer
from app.adapters.outbound.postgres.accounts import (
    fetch_balances,
    fetch_debts,
    fetch_products_held,
    fetch_profile,
)
from app.adapters.outbound.postgres.audit import record_decision
from app.domain.accounts import (
    DEBT_TYPES,
    balance_totals,
    credit_available,
    present,
    tenure_years,
)

mcp = FastMCP("accounts")
DebtType = Literal["Tarjeta Crédito", "Préstamo Personal", "Préstamo Hipotecario"]


@mcp.tool
async def get_balances(ctx: Context, product_type: str | None = None) -> dict:
    """Balances of the authenticated customer's products, and their totals.

    product_type filters to one type: "Cuenta Ahorro", "Cuenta Corriente", "Tarjeta Crédito",
    "Tarjeta Débito", "Préstamo Personal", "Préstamo Hipotecario", "Inversión", "Seguro".
    Omit it to get every product. Card and account numbers come masked (last 4 digits).
    `totals` adds up the Active products per group (deposits, investments, debt) and currency:
    use it for "how much do I have in total" and never add different currencies yourself.
    `credit_available` is what is left of a credit card's limit.
    """
    customer_id = session_customer(ctx)
    rows = await fetch_balances(customer_id, product_type)
    products = []
    for row in rows:
        available = credit_available(row)
        products.append(present(row | {"credit_available": available}))
    await record_decision(
        "get_balances",
        {"customer_id": customer_id, "product_type": product_type},
        "allowed",
        f"products={len(products)}",
        executed=True,
    )
    return {
        "products": products,
        "totals": balance_totals(rows),
        "evidence_lookup": "get_balances",
    }


@mcp.tool
async def get_debts(ctx: Context, product_type: DebtType | None = None) -> dict:
    """What the authenticated customer owes on credit cards and loans, and when to pay.

    Per product: `debt` (current balance owed), `interest_rate` (annual %), `days_past_due`,
    `statement_date` (cut-off), `due_date` (pay by), `statement_balance` (cards),
    `minimum_payment` (cards: the minimum due, past due included; loans: the installment),
    `past_due_amount` and `remaining_installments` (loans). product_type narrows to one type.
    The dates and payment amounts are illustrative figures generated by the team
    (`billing_provenance`), stated as of `as_of`: say so when you give them. A field that is
    absent is unknown, never zero.
    """
    customer_id = session_customer(ctx)
    rows = await fetch_debts(customer_id, [product_type] if product_type else list(DEBT_TYPES))
    as_of = {row.pop("as_of") for row in rows} - {None}  # one date for the whole load
    await record_decision(
        "get_debts",
        {"customer_id": customer_id, "product_type": product_type},
        "allowed",
        f"products={len(rows)}",
        executed=True,
    )
    return present({"as_of": min(as_of, default=None)}) | {
        "debts": [present(row) for row in rows],
        "billing_provenance": "team_generated",
        "evidence_lookup": "get_debts",
    }


@mcp.tool
async def get_profile(ctx: Context) -> dict:
    """The authenticated customer's own profile: name, city, country, segment, language, status,
    since when they are a customer (`customer_since`, `tenure_years`) and how many products of
    each type they hold. A field that is absent is not on record."""
    customer_id = session_customer(ctx)
    profile = await fetch_profile(customer_id)
    if profile is None:
        return {"error": "No profile on record for this customer."}
    held = await fetch_products_held(customer_id)
    await record_decision("get_profile", {"customer_id": customer_id}, "allowed", None, True)
    as_of = profile.pop("as_of")
    return present(profile | {"tenure_years": tenure_years(profile["customer_since"], as_of)}) | {
        "products": held,
        "evidence_lookup": "get_profile",
    }


if __name__ == "__main__":
    mcp.run()
